<?php
return array(
	'album'=>'Album',
	'banner'=>'Banner',
	'setting'=>'Cấu hình',
	'qa'=>'Hỏi đáp',
	'image'=>'Image',
	'keyword'=>'Keyword',
	'contact'=>'Liên hệ',
	'menu'=>'Menu',
	'language'=>'Ngôn ngữ',
	'role'=>'Quản lý quyền',
	'event'=>'Sự kiện',
	'news'=>'Tin tức',	
	'preschool'=>'Mẫu giáo',
	'primarySchool'=>'Tiểu học',
	'highSchool'=>'THCS&THPT',
	'notice'=>'Thông báo',
	'staticPage'=>'Trang giới thiệu',
	'entrance'=>'Tuyển sinh',
	'user'=>'User',
	'galleryVideo'=>'Video',	
);